name: Deploy to Azure

on:
  push:
    branches:
      - main  # Trigger deployment when pushing to the 'main' branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-22.04  # Use Ubuntu 22.04 for the job

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3  # Check out the repository code

    - name: Set up Node.js
      uses: actions/setup-node@v3  # Set up Node.js
      with:
        node-version: '20.x'  # Ensure the correct version of Node.js is being used

    - name: Install dependencies
      run: npm install  # Install the necessary dependencies

    - name: Build the app
      run: npm run build  # Run the build command (if needed, based on your package.json)

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2  # Deploy the app to Azure Web App
      with:
        app-name: "web-test"  # Replace with your actual Azure App Service name
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}  # Secret holding the publish profile
        package: .  # Specifies the path to the app to deploy (current directory in this case)
